import {FotoFestival} from './FotoFestival';

export class FotoUtil {
    static DAY_ZHAI_GUAN_YIN: string[] = ['1-8', '2-7', '2-9', '2-19', '3-3', '3-6', '3-13', '4-22', '5-3', '5-17', '6-16', '6-18', '6-19', '6-23', '7-13', '8-16', '9-19', '9-23', '10-2', '11-19', '11-24', '12-25'];
    static XIU_27: string[] = [
        '{xx.jiao}',
        '{xx.kang}',
        '{xx.di}',
        '{xx.fang}',
        '{xx.xin}',
        '{xx.tail}',
        '{xx.ji}',
        '{xx.dou}',
        '{xx.nv}',
        '{xx.xu}',
        '{xx.wei}',
        '{xx.shi}',
        '{xx.qiang}',
        '{xx.kui}',
        '{xx.lou}',
        '{xx.vei}',
        '{xx.mao}',
        '{xx.bi}',
        '{xx.zi}',
        '{xx.can}',
        '{xx.jing}',
        '{xx.gui}',
        '{xx.liu}',
        '{xx.xing}',
        '{xx.zhang}',
        '{xx.yi}',
        '{xx.zhen}'
    ];
    private static XIU_OFFSET: number[] = [11, 13, 15, 17, 19, 21, 24, 0, 2, 4, 7, 9];
    static _DJ = '敏感词';
    static _JS = '敏感词';
    static _SS = '敏感词';
    static _XL = '敏感词';
    static _JW = '敏感词';

    static _Y = new FotoFestival('敏感词');
    static _T = new FotoFestival('敏感词', '', true);
    static _D = new FotoFestival('敏感词', FotoUtil._DJ, true);
    static _S = new FotoFestival('敏感词', FotoUtil._DJ, true);
    static _W = new FotoFestival('敏感词', FotoUtil._DJ, true);
    static _H = new FotoFestival('敏感词', FotoUtil._JS, true);
    static _L = new FotoFestival('敏感词', FotoUtil._JS, true);
    static _J = new FotoFestival('敏感词', '敏感词，敏感词');
    static _R = new FotoFestival('敏感词', '敏感词', true, '敏感词');
    static _M = new FotoFestival('敏感词', FotoUtil._JS, true, '敏感词，敏感词');
    static _HH = new FotoFestival('敏感词', FotoUtil._JS, true, '敏感词，敏感词');

    static FESTIVAL: { [key: string]: FotoFestival[] } = {
        '1-1': [new FotoFestival('敏感词，敏感词', FotoUtil._XL), FotoUtil._S],
        '1-3': [new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._D],
        '1-5': [new FotoFestival('敏感词')],
        '1-6': [new FotoFestival('敏感词'), FotoUtil._L],
        '1-7': [new FotoFestival('敏感词', FotoUtil._SS)],
        '1-8': [new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._T],
        '1-9': [new FotoFestival('敏感词', FotoUtil._DJ)],
        '1-13': [FotoUtil._Y],
        '1-14': [new FotoFestival('敏感词', FotoUtil._JS), FotoUtil._T],
        '1-15': [new FotoFestival('敏感词', FotoUtil._JS), new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._W, FotoUtil._T],
        '1-16': [new FotoFestival('敏感词', FotoUtil._JS)],
        '1-19': [new FotoFestival('敏感词')],
        '1-23': [new FotoFestival('敏感词'), FotoUtil._T],
        '1-25': [FotoUtil._H, new FotoFestival('敏感词', '敏感词，敏感词')],
        '1-27': [FotoUtil._D],
        '1-28': [FotoUtil._R],
        '1-29': [FotoUtil._T],
        '1-30': [FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '2-1': [new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._S],
        '2-2': [new FotoFestival('敏感词', FotoUtil._DJ), new FotoFestival('敏感词', '敏感词')],
        '2-3': [new FotoFestival('敏感词', FotoUtil._XL), FotoUtil._D],
        '2-6': [new FotoFestival('敏感词'), FotoUtil._L],
        '2-8': [new FotoFestival('敏感词', FotoUtil._DJ), new FotoFestival('敏感词', FotoUtil._DJ), new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._T],
        '2-11': [FotoUtil._Y],
        '2-14': [FotoUtil._T],
        '2-15': [new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词', FotoUtil._XL, true), FotoUtil._T],
        '2-17': [new FotoFestival('敏感词')],
        '2-18': [new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词', FotoUtil._XL)],
        '2-19': [new FotoFestival('敏感词', FotoUtil._DJ)],
        '2-21': [new FotoFestival('敏感词')],
        '2-23': [FotoUtil._T],
        '2-25': [FotoUtil._H],
        '2-27': [FotoUtil._D],
        '2-28': [FotoUtil._R],
        '2-29': [FotoUtil._T],
        '2-30': [FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '3-1': [new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._S],
        '3-3': [new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._D],
        '3-6': [FotoUtil._L],
        '3-8': [new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._T],
        '3-9': [new FotoFestival('敏感词', '敏感词'), FotoUtil._Y],
        '3-12': [new FotoFestival('敏感词')],
        '3-14': [FotoUtil._T],
        '3-15': [new FotoFestival('敏感词', FotoUtil._DJ), new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._W, FotoUtil._T],
        '3-16': [new FotoFestival('敏感词', FotoUtil._DJ)],
        '3-19': [new FotoFestival('敏感词'), new FotoFestival('敏感词'), new FotoFestival('敏感词')],
        '3-20': [new FotoFestival('敏感词', FotoUtil._SS), new FotoFestival('敏感词')],
        '3-23': [FotoUtil._T],
        '3-25': [FotoUtil._H],
        '3-27': [new FotoFestival('敏感词'), FotoUtil._D],
        '3-28': [FotoUtil._R, new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词')],
        '3-29': [FotoUtil._T],
        '3-30': [FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '4-1': [new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._S],
        '4-3': [FotoUtil._D],
        '4-4': [new FotoFestival('敏感词', '敏感词'), new FotoFestival('敏感词')],
        '4-6': [FotoUtil._L],
        '4-7': [new FotoFestival('敏感词、敏感词、敏感词', FotoUtil._JS), FotoUtil._Y],
        '4-8': [new FotoFestival('敏感词', FotoUtil._DJ), new FotoFestival('敏感词', '敏感词'), new FotoFestival('敏感词', '敏感词'), new FotoFestival('敏感词'), FotoUtil._T],
        '4-14': [new FotoFestival('敏感词', FotoUtil._JS), FotoUtil._T],
        '4-15': [FotoUtil._W, new FotoFestival('敏感词'), FotoUtil._T],
        '4-16': [new FotoFestival('敏感词', FotoUtil._SS)],
        '4-17': [new FotoFestival('敏感词', FotoUtil._DJ)],
        '4-18': [new FotoFestival('敏感词', FotoUtil._SS), new FotoFestival('敏感词', FotoUtil._SS)],
        '4-20': [new FotoFestival('敏感词')],
        '4-23': [FotoUtil._T],
        '4-25': [FotoUtil._H],
        '4-27': [FotoUtil._D],
        '4-28': [FotoUtil._R],
        '4-29': [FotoUtil._T],
        '4-30': [FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '5-1': [new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._S],
        '5-3': [FotoUtil._D],
        '5-5': [new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词', FotoUtil._XL), FotoUtil._J, FotoUtil._Y],
        '5-6': [FotoUtil._J, FotoUtil._L],
        '5-7': [FotoUtil._J],
        '5-8': [new FotoFestival('敏感词'), FotoUtil._T],
        '5-11': [new FotoFestival('敏感词', FotoUtil._SS), new FotoFestival('敏感词')],
        '5-12': [new FotoFestival('敏感词')],
        '5-13': [new FotoFestival('敏感词', FotoUtil._XL)],
        '5-14': [new FotoFestival('敏感词', FotoUtil._JW), FotoUtil._T],
        '5-15': [FotoUtil._W, FotoUtil._J, FotoUtil._T],
        '5-16': [new FotoFestival('敏感词', FotoUtil._JW), new FotoFestival('敏感词', FotoUtil._JW)],
        '5-17': [FotoUtil._J],
        '5-18': [new FotoFestival('敏感词')],
        '5-22': [new FotoFestival('敏感词', FotoUtil._DJ)],
        '5-23': [FotoUtil._T],
        '5-25': [FotoUtil._J, FotoUtil._H],
        '5-26': [FotoUtil._J],
        '5-27': [FotoUtil._J, FotoUtil._D],
        '5-28': [FotoUtil._R],
        '5-29': [FotoUtil._T],
        '5-30': [FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '6-1': [FotoUtil._S],
        '6-3': [new FotoFestival('敏感词'), FotoUtil._D, FotoUtil._Y],
        '6-5': [new FotoFestival('敏感词', FotoUtil._SS)],
        '6-6': [new FotoFestival('敏感词', FotoUtil._SS), FotoUtil._L],
        '6-8': [FotoUtil._T],
        '6-10': [new FotoFestival('敏感词')],
        '6-14': [FotoUtil._T],
        '6-15': [FotoUtil._W, FotoUtil._T],
        '6-19': [new FotoFestival('敏感词', FotoUtil._DJ)],
        '6-23': [new FotoFestival('敏感词', '敏感词'), FotoUtil._T],
        '6-24': [new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词', FotoUtil._XL)],
        '6-25': [FotoUtil._H],
        '6-27': [FotoUtil._D],
        '6-28': [FotoUtil._R],
        '6-29': [FotoUtil._T],
        '6-30': [FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '7-1': [FotoUtil._S, FotoUtil._Y],
        '7-3': [FotoUtil._D],
        '7-5': [new FotoFestival('敏感词', FotoUtil._SS, false, '敏感词')],
        '7-6': [FotoUtil._L],
        '7-7': [new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词', FotoUtil._XL)],
        '7-8': [FotoUtil._T],
        '7-10': [new FotoFestival('敏感词', '', false, '敏感词')],
        '7-12': [new FotoFestival('敏感词')],
        '7-13': [new FotoFestival('敏感词', FotoUtil._JS)],
        '7-14': [new FotoFestival('敏感词', FotoUtil._JS), FotoUtil._T],
        '7-15': [FotoUtil._W, new FotoFestival('敏感词', FotoUtil._DJ), new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._T],
        '7-16': [new FotoFestival('敏感词', FotoUtil._JS)],
        '7-18': [new FotoFestival('敏感词', FotoUtil._DJ)],
        '7-19': [new FotoFestival('敏感词', FotoUtil._DJ)],
        '7-22': [new FotoFestival('敏感词', FotoUtil._XL)],
        '7-23': [FotoUtil._T],
        '7-25': [FotoUtil._H],
        '7-27': [FotoUtil._D],
        '7-28': [FotoUtil._R],
        '7-29': [FotoUtil._Y, FotoUtil._T],
        '7-30': [new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '8-1': [FotoUtil._S, new FotoFestival('敏感词')],
        '8-3': [FotoUtil._D, new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词', '敏感词')],
        '8-5': [new FotoFestival('敏感词', FotoUtil._DJ)],
        '8-6': [FotoUtil._L],
        '8-8': [FotoUtil._T],
        '8-10': [new FotoFestival('敏感词')],
        '8-12': [new FotoFestival('敏感词')],
        '8-14': [FotoUtil._T],
        '8-15': [FotoUtil._W, new FotoFestival('敏感词', '敏感词', false, '敏感词'), FotoUtil._T],
        '8-16': [new FotoFestival('敏感词', '敏感词')],
        '8-18': [new FotoFestival('敏感词', '', false, '敏感词，敏感词')],
        '8-23': [new FotoFestival('敏感词'), FotoUtil._T],
        '8-24': [new FotoFestival('敏感词')],
        '8-25': [FotoUtil._H],
        '8-27': [FotoUtil._D, new FotoFestival('敏感词', FotoUtil._XL), FotoUtil._Y],
        '8-28': [FotoUtil._R, new FotoFestival('敏感词')],
        '8-29': [FotoUtil._T],
        '8-30': [new FotoFestival('敏感词', '敏感词'), FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '9-1': [FotoUtil._S, new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词', FotoUtil._DJ, false, '敏感词')],
        '9-3': [FotoUtil._D, new FotoFestival('敏感词')],
        '9-6': [FotoUtil._L],
        '9-8': [FotoUtil._T],
        '9-9': [new FotoFestival('敏感词', FotoUtil._XL), new FotoFestival('敏感词'), new FotoFestival('敏感词')],
        '9-10': [new FotoFestival('敏感词', FotoUtil._DJ)],
        '9-11': [new FotoFestival('敏感词')],
        '9-13': [new FotoFestival('敏感词')],
        '9-14': [FotoUtil._T],
        '9-15': [FotoUtil._W, FotoUtil._T],
        '9-17': [new FotoFestival('敏感词', '敏感词')],
        '9-19': [new FotoFestival('敏感词', FotoUtil._JS), new FotoFestival('敏感词', FotoUtil._JS)],
        '9-23': [FotoUtil._T],
        '9-25': [FotoUtil._H, FotoUtil._Y],
        '9-27': [FotoUtil._D],
        '9-28': [FotoUtil._R],
        '9-29': [FotoUtil._T],
        '9-30': [new FotoFestival('敏感词', '敏感词'), FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '10-1': [FotoUtil._S, new FotoFestival('敏感词', FotoUtil._DJ), new FotoFestival('敏感词', '敏感词')],
        '10-3': [FotoUtil._D, new FotoFestival('敏感词')],
        '10-5': [new FotoFestival('敏感词', FotoUtil._JS), new FotoFestival('敏感词', FotoUtil._JS)],
        '10-6': [FotoUtil._L, new FotoFestival('敏感词', FotoUtil._DJ)],
        '10-8': [new FotoFestival('敏感词', '', false, '敏感词'), FotoUtil._T],
        '10-10': [new FotoFestival('敏感词', '敏感词')],
        '10-11': [new FotoFestival('敏感词')],
        '10-14': [new FotoFestival('敏感词', FotoUtil._JS), FotoUtil._T],
        '10-15': [FotoUtil._W, new FotoFestival('敏感词', FotoUtil._DJ), new FotoFestival('敏感词', FotoUtil._DJ), FotoUtil._T],
        '10-16': [new FotoFestival('敏感词', FotoUtil._JS), FotoUtil._T],
        '10-23': [FotoUtil._Y, FotoUtil._T],
        '10-25': [FotoUtil._H],
        '10-27': [FotoUtil._D, new FotoFestival('敏感词')],
        '10-28': [FotoUtil._R],
        '10-29': [FotoUtil._T],
        '10-30': [FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '11-1': [FotoUtil._S],
        '11-3': [FotoUtil._D],
        '11-4': [new FotoFestival('敏感词', FotoUtil._XL)],
        '11-6': [new FotoFestival('敏感词')],
        '11-8': [FotoUtil._T],
        '11-11': [new FotoFestival('敏感词', FotoUtil._DJ), new FotoFestival('敏感词', FotoUtil._DJ)],
        '11-14': [FotoUtil._T],
        '11-15': [new FotoFestival('敏感词', '敏感词 敏感词'), new FotoFestival('敏感词', '敏感词 敏感词')],
        '11-17': [new FotoFestival('敏感词')],
        '11-19': [new FotoFestival('敏感词', '敏感词')],
        '11-21': [FotoUtil._Y],
        '11-23': [new FotoFestival('敏感词', '敏感词'), FotoUtil._T],
        '11-25': [new FotoFestival('敏感词', '敏感词'), FotoUtil._H],
        '11-26': [new FotoFestival('敏感词')],
        '11-27': [FotoUtil._D],
        '11-28': [FotoUtil._R],
        '11-29': [FotoUtil._T],
        '11-30': [FotoUtil._HH, FotoUtil._M, FotoUtil._T],
        '12-1': [FotoUtil._S],
        '12-3': [FotoUtil._D],
        '12-6': [new FotoFestival('敏感词', FotoUtil._JS), FotoUtil._L],
        '12-7': [new FotoFestival('敏感词', '敏感词')],
        '12-8': [new FotoFestival('敏感词', FotoUtil._DJ), new FotoFestival('敏感词'), FotoUtil._T, new FotoFestival('敏感词，敏感词', FotoUtil._DJ)],
        '12-12': [new FotoFestival('敏感词')],
        '12-14': [FotoUtil._T],
        '12-15': [FotoUtil._W, FotoUtil._T],
        '12-16': [new FotoFestival('敏感词')],
        '12-19': [FotoUtil._Y],
        '12-20': [new FotoFestival('敏感词', '敏感词')],
        '12-21': [new FotoFestival('敏感词')],
        '12-23': [new FotoFestival('敏感词'), FotoUtil._T],
        '12-24': [new FotoFestival('敏感词', '敏感词')],
        '12-25': [new FotoFestival('敏感词，敏感词', '敏感词'), FotoUtil._H],
        '12-27': [FotoUtil._D],
        '12-28': [FotoUtil._R],
        '12-29': [new FotoFestival('敏感词'), FotoUtil._T],
        '12-30': [new FotoFestival('敏感词，敏感词', '敏感词')]
    };

    static OTHER_FESTIVAL: { [key: string]: string[] } = {
        '1-1': ['敏感词'],
        '1-6': ['敏感词'],
        '2-8': ['敏感词'],
        '2-15': ['敏感词'],
        '2-19': ['敏感词'],
        '2-21': ['敏感词'],
        '3-16': ['敏感词'],
        '4-4': ['敏感词'],
        '4-8': ['敏感词'],
        '4-15': ['敏感词'],
        '4-28': ['敏感词'],
        '5-13': ['敏感词'],
        '6-3': ['敏感词'],
        '6-19': ['敏感词'],
        '7-13': ['敏感词'],
        '7-15': ['敏感词'],
        '7-24': ['敏感词'],
        '7-30': ['敏感词'],
        '8-15': ['敏感词'],
        '8-22': ['敏感词'],
        '9-9': ['敏感词'],
        '9-19': ['敏感词'],
        '9-30': ['敏感词'],
        '10-5': ['敏感词'],
        '10-20': ['敏感词'],
        '11-17': ['敏感词'],
        '11-19': ['敏感词'],
        '12-8': ['敏感词'],
        '12-23': ['敏感词'],
        '12-29': ['敏感词']
    };

    static getXiu(month: number, day: number): string {
        return FotoUtil.XIU_27[(FotoUtil.XIU_OFFSET[Math.abs(month)-1] + day - 1) % FotoUtil.XIU_27.length];
    }
}
